name: "PR Title Check"

on:
  pull_request:
    types: [edited, opened, synchronize, reopened]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: naveenk1223/action-pr-title@master
        with:
          regex: "PR-[0-9]{1,5}: .+" # Regex the title should match.
